#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ApptentiveDemo.Resource", IsApplication=true)]

namespace ApptentiveDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down_out = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up_in = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050030
			public const int apptentive_about_link = 2131034160;
			
			// aapt resource value: 0x7f05002f
			public const int apptentive_about_text = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int apptentive_about_title = 2131034158;
			
			// aapt resource value: 0x7f050031
			public const int apptentive_about_version = 2131034161;
			
			// aapt resource value: 0x7f05001d
			public const int apptentive_activity_background = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int apptentive_activity_frame = 2131034140;
			
			// aapt resource value: 0x7f05002d
			public const int apptentive_branding_text = 2131034157;
			
			// aapt resource value: 0x7f050006
			public const int apptentive_dialog_background = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int apptentive_dialog_body_text = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int apptentive_dialog_button_negative = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int apptentive_dialog_button_negative_border_focused = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int apptentive_dialog_button_negative_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int apptentive_dialog_button_negative_disabled_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int apptentive_dialog_button_negative_focused = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int apptentive_dialog_button_negative_focused_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int apptentive_dialog_button_negative_pressed = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int apptentive_dialog_button_negative_pressed_text = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int apptentive_dialog_button_negative_text = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int apptentive_dialog_button_positive = 2131034131;
			
			// aapt resource value: 0x7f05001b
			public const int apptentive_dialog_button_positive_border_focused = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int apptentive_dialog_button_positive_disabled = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int apptentive_dialog_button_positive_disabled_text = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int apptentive_dialog_button_positive_focused = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int apptentive_dialog_button_positive_focused_text = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int apptentive_dialog_button_positive_pressed = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int apptentive_dialog_button_positive_pressed_text = 2131034138;
			
			// aapt resource value: 0x7f050014
			public const int apptentive_dialog_button_positive_text = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int apptentive_dialog_form_text = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int apptentive_dialog_title_text = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int apptentive_message_auto_separator = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int apptentive_message_auto_text = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int apptentive_message_center_header_text_shadow = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int apptentive_message_center_timestamp = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int apptentive_message_sender_text = 2131034113;
			
			// aapt resource value: 0x7f05002a
			public const int apptentive_survey_answer_text = 2131034154;
			
			// aapt resource value: 0x7f050020
			public const int apptentive_survey_content_background = 2131034144;
			
			// aapt resource value: 0x7f05002b
			public const int apptentive_survey_footer_background = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int apptentive_survey_question_answer_text = 2131034152;
			
			// aapt resource value: 0x7f050021
			public const int apptentive_survey_question_background = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int apptentive_survey_question_instruction_background_invalid = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int apptentive_survey_question_instruction_background_valid = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int apptentive_survey_question_instruction_text = 2131034146;
			
			// aapt resource value: 0x7f050025
			public const int apptentive_survey_question_instruction_text_invalid = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int apptentive_survey_question_instruction_text_valid = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int apptentive_survey_question_separator = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int apptentive_survey_question_text = 2131034151;
			
			// aapt resource value: 0x7f05001f
			public const int apptentive_survey_separator = 2131034143;
			
			// aapt resource value: 0x7f05002c
			public const int apptentive_survey_thank_you_dialog_border = 2131034156;
			
			// aapt resource value: 0x7f05001e
			public const int apptentive_survey_title_text = 2131034142;
			
			// aapt resource value: 0x7f050000
			public const int apptentive_text_message_text = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060005
			public const int apptentive_activity_side_padding = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int apptentive_activity_side_padding_360dp_land = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int apptentive_activity_side_padding_360dp_port = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int apptentive_activity_side_padding_600dp_land = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int apptentive_activity_side_padding_600dp_port = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int apptentive_activity_vertical_padding = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int apptentive_activity_vertical_padding_360dp_land = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int apptentive_activity_vertical_padding_360dp_port = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int apptentive_activity_vertical_padding_600dp_land = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int apptentive_activity_vertical_padding_600dp_port = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int apptentive_text_large = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int apptentive_text_medium = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int apptentive_text_medium_small = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int apptentive_text_small = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int apptentive_text_small_tiny = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android_ic_action_photo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_ic_action_send = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_ic_menu_start_conversation = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int android_textfield_activated_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int android_textfield_default = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptentive_activity_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apptentive_blue_denim = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apptentive_dialog_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apptentive_dialog_background_with_border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int apptentive_dialog_negative_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int apptentive_dialog_negative_button_text = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int apptentive_dialog_positive_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int apptentive_dialog_positive_button_text = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int apptentive_grey_denim = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int apptentive_grey_texture = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int apptentive_header_background_50px = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int apptentive_icon_small = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int apptentive_logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int apptentive_logo_black = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int apptentive_logo_reverse = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int apptentive_message_bubble_incoming_top = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int apptentive_message_bubble_outgoing_top = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int apptentive_message_center_background_denim = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int apptentive_message_center_header_denim = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int apptentive_paper_bg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int apptentive_survey_question_background = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int apptentive_survey_question_background_invalid = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int apptentive_survey_send_button = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int apptentive_survey_send_button_text = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int avatar = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int list_item_handle_25x20 = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070032
			public const int MyButton = 2131165234;
			
			// aapt resource value: 0x7f070001
			public const int about_description_link = 2131165185;
			
			// aapt resource value: 0x7f07002b
			public const int answer_container = 2131165227;
			
			// aapt resource value: 0x7f070031
			public const int answer_text = 2131165233;
			
			// aapt resource value: 0x7f070004
			public const int apptentive_branding_view = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int apptentive_file_message_image = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int apptentive_file_message_text = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int apptentive_intro_instructions_container = 2131165209;
			
			// aapt resource value: 0x7f07000a
			public const int apptentive_message_auto_body = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int apptentive_message_auto_frame = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int apptentive_message_auto_title = 2131165193;
			
			// aapt resource value: 0x7f070021
			public const int apptentive_message_avatar = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int apptentive_message_body = 2131165218;
			
			// aapt resource value: 0x7f070012
			public const int apptentive_message_center_attach_button = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int apptentive_message_center_header_title = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int apptentive_message_center_list = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int apptentive_message_center_message = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int apptentive_message_center_powered_by_apptentive = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int apptentive_message_center_powered_by_text = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int apptentive_message_center_root = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int apptentive_message_center_send = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int apptentive_message_center_view = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int apptentive_message_sender_name = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int apptentive_message_timestamp = 2131165219;
			
			// aapt resource value: 0x7f07000d
			public const int apptentive_text_message_text = 2131165197;
			
			// aapt resource value: 0x7f070017
			public const int body = 2131165207;
			
			// aapt resource value: 0x7f070030
			public const int checkbox = 2131165232;
			
			// aapt resource value: 0x7f07002e
			public const int choice = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int choice_container = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int choice_text = 2131165231;
			
			// aapt resource value: 0x7f07001e
			public const int close = 2131165214;
			
			// aapt resource value: 0x7f070026
			public const int description = 2131165222;
			
			// aapt resource value: 0x7f07001a
			public const int email = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int image = 2131165198;
			
			// aapt resource value: 0x7f07001b
			public const int message = 2131165211;
			
			// aapt resource value: 0x7f070006
			public const int no = 2131165190;
			
			// aapt resource value: 0x7f07001c
			public const int no_thanks = 2131165212;
			
			// aapt resource value: 0x7f070018
			public const int ok = 2131165208;
			
			// aapt resource value: 0x7f070002
			public const int privacy_link = 2131165186;
			
			// aapt resource value: 0x7f07002c
			public const int question_background_validation = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int question_instructions = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int question_title = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int question_top_separater = 2131165226;
			
			// aapt resource value: 0x7f070027
			public const int questions = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int rate = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int remind = 2131165221;
			
			// aapt resource value: 0x7f07001d
			public const int send = 2131165213;
			
			// aapt resource value: 0x7f070005
			public const int title = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int version = 2131165187;
			
			// aapt resource value: 0x7f07001f
			public const int view_messages = 2131165215;
			
			// aapt resource value: 0x7f070007
			public const int yes = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int apptentive_about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int apptentive_about_content = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int apptentive_branding = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int apptentive_enjoyment_dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int apptentive_enjoyment_dialog_content = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int apptentive_message_auto = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int apptentive_message_body_file = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int apptentive_message_body_text = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int apptentive_message_center = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int apptentive_message_center_attachment_preview = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int apptentive_message_center_attachment_preview_content = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int apptentive_message_center_content = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int apptentive_message_center_email_validation = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int apptentive_message_center_email_validation_content = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int apptentive_message_center_intro_dialog = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int apptentive_message_center_intro_dialog_content = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int apptentive_message_center_thank_you_dialog = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int apptentive_message_center_thank_you_dialog_content = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int apptentive_message_incoming = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int apptentive_message_outgoing = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int apptentive_rating_dialog = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int apptentive_rating_dialog_content = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int apptentive_survey = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int apptentive_survey_content = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int apptentive_survey_question_base = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int apptentive_survey_question_multichoice = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int apptentive_survey_question_multichoice_choice = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int apptentive_survey_question_singleline = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int apptentive_survey_thank_you_dialog = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int apptentive_survey_thank_you_dialog_content = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Main = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080036
			public const int ApplicationName = 2131230774;
			
			// aapt resource value: 0x7f080035
			public const int Hello = 2131230773;
			
			// aapt resource value: 0x7f080015
			public const int apptentive_about_description = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int apptentive_about_description_link = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int apptentive_about_privacy = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int apptentive_about_privacy_link = 2131230744;
			
			// aapt resource value: 0x7f080014
			public const int apptentive_about_title = 2131230740;
			
			// aapt resource value: 0x7f080005
			public const int apptentive_developer = 2131230725;
			
			// aapt resource value: 0x7f080028
			public const int apptentive_dialog_email_validation_failed_body = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int apptentive_dialog_email_validation_failed_title = 2131230759;
			
			// aapt resource value: 0x7f080019
			public const int apptentive_do_you_love_this_app = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int apptentive_edittext_hint_email = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int apptentive_edittext_hint_email_required = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int apptentive_give_feedback = 2131230728;
			
			// aapt resource value: 0x7f080020
			public const int apptentive_intro_dialog_body = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int apptentive_intro_dialog_edittext_hint = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int apptentive_intro_dialog_title_default = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int apptentive_intro_dialog_title_no_love = 2131230750;
			
			// aapt resource value: 0x7f080030
			public const int apptentive_message_auto_body_manual = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int apptentive_message_auto_body_no_love = 2131230769;
			
			// aapt resource value: 0x7f08002e
			public const int apptentive_message_center_attachment_title = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int apptentive_message_center_compose_hint = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int apptentive_message_center_title = 2131230764;
			
			// aapt resource value: 0x7f08002f
			public const int apptentive_message_sent_timestamp_format = 2131230767;
			
			// aapt resource value: 0x7f080002
			public const int apptentive_no = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int apptentive_no_thanks = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int apptentive_ok = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int apptentive_oops = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int apptentive_optional = 2131230734;
			
			// aapt resource value: 0x7f080013
			public const int apptentive_powered_by_apptentive = 2131230739;
			
			// aapt resource value: 0x7f08001b
			public const int apptentive_rate_this_app = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int apptentive_rating_error = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int apptentive_rating_message_fs = 2131230746;
			
			// aapt resource value: 0x7f080033
			public const int apptentive_rating_provider_no_amazon_appstore = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int apptentive_rating_provider_no_google_play = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int apptentive_rating_provider_no_mikandi = 2131230772;
			
			// aapt resource value: 0x7f08001c
			public const int apptentive_rating_remind = 2131230748;
			
			// aapt resource value: 0x7f08000d
			public const int apptentive_required = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int apptentive_send = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int apptentive_sending = 2131230735;
			
			// aapt resource value: 0x7f080003
			public const int apptentive_skip = 2131230723;
			
			// aapt resource value: 0x7f080029
			public const int apptentive_survey_header = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int apptentive_survey_send_response = 2131230763;
			
			// aapt resource value: 0x7f08002a
			public const int apptentive_survey_singleline_hint = 2131230762;
			
			// aapt resource value: 0x7f08000b
			public const int apptentive_thank_you = 2131230731;
			
			// aapt resource value: 0x7f080022
			public const int apptentive_thank_you_dialog_body = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int apptentive_thank_you_dialog_body_message_center_disabled = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int apptentive_thank_you_dialog_body_message_center_disabled_email_required = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int apptentive_thank_you_dialog_close = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int apptentive_thank_you_dialog_view_messages = 2131230758;
			
			// aapt resource value: 0x7f080009
			public const int apptentive_thanks = 2131230729;
			
			// aapt resource value: 0x7f080010
			public const int apptentive_version = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int apptentive_were_sorry = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int apptentive_yes = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int apptentive_you = 2131230724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f09000d
			public const int Apptentive_Theme_Transparent = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int ApptentiveHeader = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int ApptentiveHeader_Denim = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int ApptentiveHeader_Plain = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int ApptentiveHeaderText = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int ApptentiveHeaderText_Default = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int ApptentiveHeaderText_Denim = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int ApptentiveHeaderText_Plain = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int ApptentiveMainArea = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int ApptentiveMainArea_Denim = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int ApptentiveMainArea_Plain = 2131296265;
			
			// aapt resource value: 0x7f090003
			public const int ApptentiveMessageCenterDrawer = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int ApptentiveMessageCenterDrawer_Denim = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int ApptentiveMessageCenterDrawer_Plain = 2131296267;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
